version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  website:
    depends_on:
      - db
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:usr/src/app

volumes:
  postgres:
